--Task#1

SELECT  [FOLLOWING].FollowedUserName, COUNT([FOLLOWING].FollowerUserName) AS Total_Followers
FROM [USERS] JOIN [FOLLOWING] 
ON [USERS].UserName = [FOLLOWING].FollowedUserName
GROUP BY [FOLLOWING].FollowedUserName
HAVING COUNT([FOLLOWING].FollowerUserName) IN
(
	SELECT  TOP(1) COUNT([FOLLOWING].FollowerUserName)
	FROM [USERS] JOIN [FOLLOWING] 
	ON [USERS].UserName = [FOLLOWING].FollowedUserName
	GROUP BY [FOLLOWING].FollowedUserName
	ORDER BY COUNT([FOLLOWING].FollowerUserName) DESC
)

--Task#2

SELECT  [FOLLOWING].FollowedUserName, COUNT([FOLLOWING].FollowerUserName) AS Total_Followers
FROM [USERS] JOIN [FOLLOWING] 
ON [USERS].UserName = [FOLLOWING].FollowedUserName
GROUP BY [FOLLOWING].FollowedUserName
HAVING COUNT([FOLLOWING].FollowerUserName) IN
(
	SELECT  TOP(1) COUNT([FOLLOWING].FollowerUserName)
	FROM [USERS] JOIN [FOLLOWING] 
	ON [USERS].UserName = [FOLLOWING].FollowedUserName
	GROUP BY [FOLLOWING].FollowedUserName
	HAVING COUNT([FOLLOWING].FollowerUserName) NOT IN
	(
		SELECT  TOP(1) COUNT([FOLLOWING].FollowerUserName)
		FROM [USERS] JOIN [FOLLOWING] 
		ON [USERS].UserName = [FOLLOWING].FollowedUserName
		GROUP BY [FOLLOWING].FollowedUserName
		ORDER BY COUNT([FOLLOWING].FollowerUserName) DESC
	)
	ORDER BY COUNT([FOLLOWING].FollowerUserName) DESC
)

--Task#3

SELECT  [USERS].UserName FROM [USERS]
WHERE [USERS].UserName NOT IN
(
	SELECT  [TWEETS].UserName FROM [TWEETS]
	GROUP BY [TWEETS].UserName
)

--Task#4

SELECT  [HASHTAGS].[Hashtag], [TWEETS].UserName, COUNT([HASHTAGS].Hashtag) AS Total_Followers
FROM [TWEETS] JOIN [HASHTAGS]
ON CHARINDEX([HASHTAGS].Hashtag,[TWEETS].Text) > 0
GROUP BY [HASHTAGS].Hashtag,[TWEETS].UserName

--Task#5

SELECT  [USERS].UserName FROM [USERS]
WHERE [USERS].UserName NOT IN
(
	SELECT [TWEETS].UserName FROM [TWEETS] JOIN [HASHTAGS]
	ON CHARINDEX('#Census',[TWEETS].Text) > 0
	GROUP BY [HASHTAGS].Hashtag,[TWEETS].UserName
)

--Task#6

SELECT  [USERS].UserName FROM [USERS]
EXCEPT
SELECT  [FOLLOWING].FollowedUserName FROM [FOLLOWING]
GROUP BY [FOLLOWING].FollowedUserName

--Task#7

SELECT  [USERS].UserName FROM [USERS]
WHERE NOT EXISTS
(
	SELECT  [FOLLOWING].FollowedUserName FROM [FOLLOWING]
	WHERE [USERS].UserName = [FOLLOWING].FollowedUserName
	GROUP BY [FOLLOWING].FollowedUserName
)

--Task#8

SELECT  [INTERESTS].Description AS MostCommonInterest FROM [INTERESTS]
WHERE [INTERESTS].InterestID IN
(
	SELECT  [INTERESTS].InterestID
	FROM [USERINTERESTS] JOIN [INTERESTS]
	ON [USERINTERESTS].InterestID = [INTERESTS].InterestID
	GROUP BY [INTERESTS].InterestID
	HAVING COUNT([INTERESTS].InterestID) IN
	(
		SELECT TOP(1) COUNT([INTERESTS].InterestID)
		FROM [USERINTERESTS] JOIN [INTERESTS]
		ON [USERINTERESTS].InterestID = [INTERESTS].InterestID
		GROUP BY [INTERESTS].InterestID
		ORDER BY COUNT([INTERESTS].InterestID) DESC
	)
)

SELECT  [INTERESTS].Description AS LeastCommonInterest FROM [INTERESTS]
WHERE [INTERESTS].InterestID IN
(
	SELECT  [INTERESTS].InterestID
	FROM [USERINTERESTS] JOIN [INTERESTS]
	ON [USERINTERESTS].InterestID = [INTERESTS].InterestID
	GROUP BY [INTERESTS].InterestID
	HAVING COUNT([INTERESTS].InterestID) IN
	(
		SELECT TOP(1) COUNT([INTERESTS].InterestID)
		FROM [USERINTERESTS] JOIN [INTERESTS]
		ON [USERINTERESTS].InterestID = [INTERESTS].InterestID
		GROUP BY [INTERESTS].InterestID
		ORDER BY COUNT([INTERESTS].InterestID) ASC
	)
)

--Task#9

SELECT [USERS].Country, COUNT([USERS].Country) AS TotalTweets
FROM [USERS] JOIN [TWEETS]
ON [USERS].UserName = [TWEETS].UserName
GROUP BY [USERS].Country
ORDER BY [USERS].Country

--Task#10

SELECT [TWEETS].UserName, COUNT([TWEETS].UserName) AS TotalTweets 
FROM [TWEETS] GROUP BY [TWEETS].UserName
HAVING COUNT([TWEETS].UserName) > 
(
	SELECT AVG([T1].TotalTweets) FROM 
		(
			SELECT [TWEETS].UserName, COUNT([TWEETS].UserName) AS TotalTweets 
			FROM [TWEETS] GROUP BY [TWEETS].UserName
		) AS T1
)

--Task#11

SELECT [FOLLOWING].FollowedUserName, COUNT([FOLLOWING].FollowerUserName) AS Total_Followers
FROM [USERS] JOIN [FOLLOWING] 
ON [USERS].UserName = [FOLLOWING].FollowerUserName
WHERE [USERS].Country LIKE '%Pakistan%'
GROUP BY [FOLLOWING].FollowedUserName
HAVING COUNT([USERS].Country) >= 1

--Task#12

SELECT  * FROM [INTERESTS]
WHERE [INTERESTS].InterestID IN
(
	SELECT  [INTERESTS].InterestID
	FROM [USERINTERESTS] JOIN [INTERESTS]
	ON [USERINTERESTS].InterestID = [INTERESTS].InterestID
	GROUP BY [INTERESTS].InterestID
	HAVING COUNT([INTERESTS].InterestID) IN
	(
		SELECT TOP(1) COUNT([INTERESTS].InterestID)
		FROM [USERINTERESTS] JOIN [INTERESTS]
		ON [USERINTERESTS].InterestID = [INTERESTS].InterestID
		GROUP BY [INTERESTS].InterestID
		ORDER BY COUNT([INTERESTS].InterestID) DESC
	)
)
